services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "" # No build step needed for JS
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Optional: Render sets this automatically